spring:
  datasource:
    url: jdbc:oracle:thin:@//10.101.0.70:1521/pael19c
    username: ALEJANDRO_BOCANEGRA
    password: NoR3cu3Rd24*
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
server:
  port: 8080
